const bringmetolife = [,
  "🎵 🎵 🎵",
  "How can you see into my eyes like open doors?",
  "Leading you down into my core where I've become so numb",
  "Without a soul, my spirit's sleeping somewhere cold",
  "Until you find it there and lead it back home",
  "🎵",
  "WAKE ME UP",
  "Wake me up inside",
  "I CAN'T WAKE UP",
  "Wake me up inside",
  "SAVE ME",
  "Call my name and save me from the dark",
  "WAKE ME UP",
  "Bid my blood to run",
  "I CAN'T WAKE UP",
  "Before I come undone",
  "SAVE ME",
  "Save me from the nothing I've become",
  "🎵",
  "Now that I know what I'm without",
  "You can't just leave me",
  "Breathe into me and make me real",
  "Bring me to life",
  "🎵",
  "WAKE ME UP",
  "Wake me up inside",
  "I CAN'T WAKE UP",
  "Wake me up inside",
  "SAVE ME",
  "Call my name and save me from the dark",
  "WAKE ME UP",
  "Bid my blood to run",
  "I CAN'T WAKE UP",
  "Before I come undone",
  "SAVE ME",
  "Save me from the nothing I've become",
  "Bring me to life",
  "I've been living a lie, there's nothing inside",
  "Bring me to life",
  "🎵",
  "Frozen inside without your touch",
  "Without your love, darling",
  "Only you are the life among the dead",
  "All this time I can't believe I couldn't see",
  "Kept in the dark but you were there in front of me",
  "I've been sleeping a thousand years it seems",
  "Got to open my eyes to everything",
  "Without a thought, without a voice, without a soul",
  "Don't let me die here",
  "There must be something more",
  "🎵",
  "WAKE ME UP",
  "Wake me up inside",
  "I CAN'T WAKE UP",
  "Wake me up inside",
  "SAVE ME",
  "Call my name and save me from the dark",
  "WAKE ME UP",
  "Bid my blood to run",
  "I CAN'T WAKE UP",
  "Before I come undone",
  "SAVE ME",
  "Save me from the nothing I've become",
  "Bring me to life",
  "I've been living a lie, there's nothing inside",
  "Bring me to life",
  "🎵 🎵 🎵"
]
module.exports = bringmetolife;
